name: CI

on:
  # Triggers the workflow on push or pull request events for all branches
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

    # Lint Dockerfiles
      - name: Lint Dockerfiles
        run: |
          echo "Linting Dockerfiles"
          for file in $(find . -name 'Dockerfile'); do
            echo "Checking $file..."
            cat $file | docker run --rm -i hadolint/hadolint || true
          done
    # Lint Shell Scripts
      - name: Lint Shell Scripts
        run: |
          echo "Linting Shell Scripts"
          for file in $(find . -name '*.sh'); do
            echo "Checking $file..."
            docker run --rm -v $(pwd):/mnt koalaman/shellcheck:stable /mnt/$file > shellcheck_report.txt 2>&1 || true
          done
          echo "ShellCheck completed. Review the errors in shellcheck_report.txt if any."
    # Lint Python Scripts
      - name: Install Python linters
        run: |
          echo "Installing Python linters"
          pip install flake8 pylint
      - name: Lint Python Scripts
        run: |
          echo "Linting Python scripts"
          for file in $(find . -name '*.py'); do
            echo "Checking $file..."
            flake8 $file --max-line-length=120 || true
            pylint $file --max-line-length=120 --disable="C0103,C0114,C0115" || true
          done
